name: Convert and Deploy

on:
  push:
    branches: [main]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Convert MD to HTML
        uses: docker://pandoc/core:2.9
        with:
          args: "-s -o index.html --template=template.html --metadata-file=metadata.yml --mathjax index.md"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
