name: Convert and Deploy

on:
  push:
    branches: [main]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc
      - name: Convert MD to HTML
        run: |
          mkdir out
          find . -name "*.md" | while read i; do o="${i%.md}"; pandoc "${i}" -s --template=template.html --toc --mathjax >> "out${o#.}.html"; done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
# find . -name "*.md" | while read i; do o="${i%.md}"; echo "./out${o#.}"; done
