name: Convert and Deploy

on:
  push:
    branches: [main]

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get -y install pandoc
      - name: Convert MD to HTML
        run: |
          mkdir out
          for f in *.md; do pandoc "$f" -s -o "out/${f%.txt}.html" --template=template.html --toc --mathjax; done
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: out
